[workspace]
members = [
    "enum_array_derive",
    "enum_array",
    "enum_array_trait", 
    "game_engine"
]
resolver = "3"

[profile.dev]
opt-level = 3
debug = false
lto = false
incremental = true
codegen-units = 256
